spring:
  datasource:
    url: jdbc:h2:file:./data/testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size : 10MB
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  h2:
    console:
      enabled: true
      path: /h2-console

server:
  port: 8080
  servlet:
    context-path:
app:
  host-url: http://localhost:8080
jwt:
  # 이 값은 Base64로 인코딩된 32바이트 이상의 문자열이어야 합니다
  secret: QU3YmVzdHNlY3JldGtleWZvcmp3dHRva2VuZ2VuZXJhdGlvbmluMjAyNA==
  expiration: 86400000    # 24시간 (밀리초 단위)

logging:
  level:
    com.yeongsi.backend: DEBUG    # 디버깅을 위한 로그 레벨 설정
    org.springframework.security: DEBUG

file:
  upload-dir: ./uploads